python main.py \
    --task shakespeare_char \
    --project test \
    --run shake \
    --save_dir /scratch/arihanth.srikar/ \
    --block_size 256 \
    --batch_size 48 \
    --train True \
    --validate_every 200 \
    --validate_for 50 \
    --set_precision True